# Generated by Django 5.1.3 on 2024-12-05 17:37

from django.db import migrations


from django.db import migrations


def add_patient_id_field(apps, schema_editor):
    # Get the User model from the historical state
    User = apps.get_model('auth', 'User')
    db_alias = schema_editor.connection.alias

    # Add the `patient_id` field
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            ALTER TABLE auth_user
            ADD COLUMN patient_id VARCHAR(150) UNIQUE NULL;
        """)

    # Optionally, set patient_id to NULL for doctor users (assuming you have a role field)
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            UPDATE auth_user
            SET patient_id = NULL
            WHERE role = 'doctor';
        """)


class Migration(migrations.Migration):

    dependencies = [
        ("appointmentapp", "0002_auto_20241205_2300"),  # Depends on the first migration
    ]

    operations = [
        migrations.RunPython(add_patient_id_field),
    ]
