# Generated by Django 5.1.3 on 2024-12-05 17:47

from django.db import migrations


from django.db import migrations

def rename_created_at_to_date_joined(apps, schema_editor):
    # Get the model for the auth_user table (User model)
    User = apps.get_model('auth', 'User')
    db_alias = schema_editor.connection.alias

    # Rename created_at back to date_joined
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            ALTER TABLE auth_user RENAME COLUMN created_at TO date_joined;
        """)

class Migration(migrations.Migration):

    dependencies = [
        # Specify the last migration in the 'auth' app, adjust it accordingly
        ("appointmentapp", "0003_auto_20241205_2307"),  # Replace this with the last migration name in the 'auth' app
    ]

    operations = [
        migrations.RunPython(rename_created_at_to_date_joined),
    ]

