# Generated by Django 5.1.3 on 2024-12-06 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointmentapp", "0005_initial"),
    ]

    operations = [
        # Rename the model from 'appointment' to 'patientbookappointment'
        migrations.RenameModel(
            old_name="Appointment",
            new_name="PatientBookAppointment",
        ),
        
        # Rename the table in the database
        migrations.AlterModelTable(
            name="patientbookappointment",
            table="patient_book_appointment",
        ),
    ]
