# Generated by Django 5.1.3 on 2024-12-06 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointmentapp", "0005_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="appointment",
            table="patient_book_appointment",
        ),
    ]
