# Generated by Django 5.1.3 on 2025-02-24 17:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointmentapp", "0008_doctorspecializations"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorschedule",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="doctorschedule",
            name="maximum_patient",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="doctorschedule",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "scheduled"),
                    ("completed", "completed"),
                    ("cancelled", "cancelled"),
                    ("rescheduled", "rescheduled"),
                ],
                default="scheduled",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="doctorschedule",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
