# Generated by Django 5.1.3 on 2025-02-24 19:03

import django_mysql.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointmentapp", "0011_rename_doctorschedule_doctoravailabilities"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctoravailabilities",
            name="status",
            field=django_mysql.models.EnumField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("rescheduled", "Rescheduled"),
                ],
                default="scheduled",
            ),
        ),
    ]
