# Generated by Django 5.1.3 on 2025-02-26 15:11

import django_mysql.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointmentapp", "0012_alter_doctoravailabilities_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorspecializations",
            name="status",
            field=django_mysql.models.EnumField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("deleted", "Deleted"),
                ],
                default="active",
            ),
        ),
        migrations.AddField(
            model_name="patientbookappointment",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="patientbookappointment",
            name="reschedule_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patientbookappointment",
            name="reschedule_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patientbookappointment",
            name="status",
            field=django_mysql.models.EnumField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("rescheduled", "Rescheduled"),
                ],
                default="scheduled",
            ),
        ),
        migrations.AddField(
            model_name="patientbookappointment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="patientbookappointment",
            name="patient_type",
            field=django_mysql.models.EnumField(
                choices=[("new", "New"), ("old", "Old")], default="new"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="patientbookappointment",
            unique_together={
                ("appointment_date", "appointment_time", "patient", "doctor")
            },
        ),
    ]
