# Generated by Django 5.1.5 on 2025-05-17 05:39

import django.db.models.deletion
import django_mysql.models
from django.conf import settings
from django.db import migrations, models, connection


def remove_fields_from_auth_user(apps, schema_editor):
    with connection.cursor() as cursor:
        try:
            cursor.execute("ALTER TABLE auth_user DROP COLUMN role;")
        except Exception:
            pass
        try:
            cursor.execute("ALTER TABLE auth_user DROP COLUMN phone_number;")
        except Exception:
            pass
        try:
            cursor.execute("ALTER TABLE auth_user DROP COLUMN address;")
        except Exception:
            pass
        try:
            cursor.execute("ALTER TABLE auth_user DROP COLUMN guardian_name;")
        except Exception:
            pass
        try:
            cursor.execute("ALTER TABLE auth_user DROP COLUMN patient_id;")
        except Exception:
            pass
        try:
            cursor.execute("ALTER TABLE auth_user DROP COLUMN gender;")
        except Exception:
            pass

class Migration(migrations.Migration):

    dependencies = [
        ('appointmentapp', '0013_doctorspecializations_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorspecializations',
            name='serviceLogo',
            field=models.ImageField(blank=True, null=True, upload_to='specializations/'),
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', django_mysql.models.EnumField(choices=[('role_doctor', 'Role_Doctor'), ('role_patient', 'Role_Patient'), ('role_admin', 'Role_Admin')], default='role_patient')),
                ('phone_number', models.TextField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('status', django_mysql.models.EnumField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deleted', 'Deleted')], default='active')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('patient_id', models.CharField(max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_details',
            },
        ),
        migrations.RunPython(remove_fields_from_auth_user),
    ]
