# Generated by Django 5.1.3 on 2025-06-05 19:15

import django_mysql.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointmentapp", "0014_doctorspecializations_servicelogo_userdetails"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("address", models.TextField(blank=True, null=True)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "user_contact",
            },
        ),
        migrations.AddField(
            model_name="userdetails",
            name="gender",
            field=django_mysql.models.EnumField(
                blank=True,
                choices=[("female", "Female"), ("male", "Male"), ("others", "Others")],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userdetails",
            name="guardian_name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
