# Generated by Django 5.1.3 on 2025-06-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointmentapp", "0015_contact_userdetails_gender_userdetails_guardian_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctoravailabilities",
            name="slot_duration",
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name="patientbookappointment",
            name="prescription_file",
            field=models.FileField(blank=True, null=True, upload_to="prescriptions/"),
        ),
        migrations.AddField(
            model_name="userdetails",
            name="experience_years",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userdetails",
            name="qualification",
            field=models.TextField(blank=True, null=True),
        ),
    ]
